### ISSUE TITLE
Mod does not work with 1.20.4

### ISSUE THREAD

**Issue by starkgate** [quat1024/templates-mod#9]
Templates 2 is crashing the game in 1.20.4, I guess some breaking changes require an update of the mod.

Here is the crash log:

```
---- Minecraft Crash Report ----
// Don't do that.
Time: 2024-02-09 22:32:44
Description: Initializing game
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'templates'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:487)
	at net.minecraft.client.main.Main.main(Main.java:223)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Caused by: java.lang.NoSuchMethodError: 'void net.minecraft.class_2269.<init>(net.minecraft.class_4970$class_2251, net.minecraft.class_8177, int, boolean)'
	at io.github.cottonmc.templates.block.TemplateButtonBlock.<init>(TemplateButtonBlock.java:34)
	at io.github.cottonmc.templates.block.TemplateButtonBlock.<init>(TemplateButtonBlock.java:30)
	at io.github.cottonmc.templates.Templates.<clinit>(Templates.java:58)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
```

**Comment by quat1024** [comment]
https://modrinth.com/mod/templates-2/version/2.4.0-fabric-1.20.4
